name: Build With CMake

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v2
     - name: Configure
       run: cmake . -DUtils_BUILD_TESTS=ON
     - name: Make
       run: make
     - name: RunTests
       run: ./Tests/UtilsTests
